language: python
python:
- '3.6'
install:
- pip install nbconvert
- jupyter nbconvert --to markdown --FilesWriter.build_directory=_posts ['20']*.ipynb

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  on:
    branch: master
  verbose: true
